version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: npm test -- --watch=false --browsers=ChromeHeadless
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Install Cypress
          command: npm install cypress
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
